[package]
name = "actor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true, features = ["default"] }
serde = { workspace = true }
rmp-serde = { workspace = true }
serde_json = { workspace = true, features = ["std"] }